### ISSUE TITLE
Support de l'authentification SSO de auth.cfp.io

### ISSUE THREAD

**Issue by sebbrousse** [breizhcamp/moneiz#6]
Est-ce qu'on se branche sur le module existant ou on refait une base de user dédié ?

**Comment by ndeloof** [comment]
il faudrait dans ce cas qu'on crée un compte pour les acheteurs suite à une vente weezevent, quitte à ce qu'au premier accès on leur demande de choisir un mdp.

**Comment by sebbrousse** [comment]
Ok, après j'ai bien saisi que pour la phase 1 on va reste sur un "weezevent as a backend".
